apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/Johanson1988/hello-gitops-app
  newName: ghcr.io/Johanson1988/hello-gitops-app
  newTag: sha-3dfa454
- name: ghcr.io/johanson1988/hello-gitops-app
  newName: ghcr.io/johanson1988/hello-gitops-app
  newTag: sha-25d4e57
